language: python
env:
  - TEST_SUITE=
  - TEST_SUITE="--selenium-only"
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get update"
  - "sudo apt-get install libpq-dev xvfb firefox"
  - "./install-dependencies.sh"
# command to run tests
script:
  - "./run-testsuite.sh ${TEST_SUITE}"
after_success: coveralls
