language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get install libpq-dev xvfb chromium-browser firefox"
  - "sudo ln -s /usr/lib/chromium-browser/chromium-browser /usr/bin/google-chrome"
  - "./install-dependencies.sh"
# command to run tests
script:
  - "./run-testsuite.sh"
  - metashare/start-solr.sh
  - sleep 10
  - source "venv/bin/activate"
  - coverage run --source=metashare manage.py manage.py test --selenium
  - deactivate
  - metashare/stop-solr.sh
after_success: coveralls
