# This file is used by travis-ci.org to test META-SHARE
# env section
# ============
# This section sets environment variables. There are two kinds of environment
# variables in travis: "global" and "matrix".
# 
# matrix variables
# -----------------
# matrix variables can be used to tell travis we want different jobs to run
# for instance to split the testsuite in two subgroups.
# Here TEST_SUITE takes two different values, so in one case the selenium
# tests run, and in the other case the rest of the tests run.
#
# global variables
# -----------------
# Common environment variables for all the jobs that will run.
#
# In order to securely use external services (such as coveralls or sauce labs) 
# with travis and github some secrets have to be shared. Travis provides
# an option to encrypt environment variables in a way that only travis can
# decrypt them and use them with the external services. By doing that, we can
# safely store encrypted keys in this file and let travis decrypt and use them.
#
language: python
env:
  global:
    # keys for using sauce labs (SAUCE_USERNAME and SAUCE_ACCESS_KEY)
    # https://docs.saucelabs.com/ci-integrations/travis-ci/
    # You will need to create a saucelabs account, free for Free Software projects.
    # keys for zeehio/META-SHARE:
    - secure: IEtbjPMMqI9qiL9JzCoqkN4t700OOG6lM83a0M9PgIpuFviC7cmUv984Vpk55yuvnIvFp5N+BzIWFbw4frxV8Al+usVZs/WHdvwMKZfoolKY4uQAeibnQzivh5DJqRjz3A8nplH953SBosseVqXW6xQBKmexNdUmA7Iz6Tjag0A=
    - secure: gi7/2rLtpYgaj4tld5eB1dL9jrRXfGAxeOVtBMAura+qKKknNE0iY0lJc6OSwY7imTRQUyg2A4xWFD0lSEw6ZQ2JpZzbCFXYXD5wsm5PPNw5lCWSUKLd1E4in9wmmQ6/tjlqH7J3DWD16Pb2AyE9RVN2jWMGUif73qygSneDudU=
    # keys for metashare/META-SHARE:
    # - secure: key_not_yet_created
    # - secure: key_not_yet_created
  matrix:
    - TEST_SUITE=
    - TEST_SUITE="--selenium-only"
    - TEST_SUITE="docs"
python:
  - "2.7"
# commands to install dependencies
install:
  - "sudo apt-get update"
  - "sudo apt-get install libpq-dev"
  - "pip install coveralls"
  - "./install-dependencies.sh"
# command to run tests
script:
  - "[ \"x$TEST_SUITE\" = \"xdocs\" ] && ./misc/test-ci/autoupdate-docs.sh || ./run-testsuite.sh ${TEST_SUITE}"
after_success:
  - "coveralls"

addons:
  sauce_connect: true

branches:
  only:
    - master

