language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get install libpq-dev xvfb chromium-browser firefox"
  - "sudo ln -s /usr/lib/chromium-browser/chromium-browser /usr/bin/google-chrome"
  - "./install-dependencies.sh"
# command to run tests
script:
  - "./run-testsuite.sh"

