language: python
env:
  global:
    - secure: IEtbjPMMqI9qiL9JzCoqkN4t700OOG6lM83a0M9PgIpuFviC7cmUv984Vpk55yuvnIvFp5N+BzIWFbw4frxV8Al+usVZs/WHdvwMKZfoolKY4uQAeibnQzivh5DJqRjz3A8nplH953SBosseVqXW6xQBKmexNdUmA7Iz6Tjag0A=
    - secure: gi7/2rLtpYgaj4tld5eB1dL9jrRXfGAxeOVtBMAura+qKKknNE0iY0lJc6OSwY7imTRQUyg2A4xWFD0lSEw6ZQ2JpZzbCFXYXD5wsm5PPNw5lCWSUKLd1E4in9wmmQ6/tjlqH7J3DWD16Pb2AyE9RVN2jWMGUif73qygSneDudU=
  matrix:
    - TEST_SUITE=
    - TEST_SUITE="--selenium-only"
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo apt-get update"
  - "sudo apt-get install libpq-dev"
  - "pip install coveralls"
  - "./install-dependencies.sh"
# command to run tests
script:
  - "./run-testsuite.sh ${TEST_SUITE}"
after_success:
  - "coveralls"

addons:
  sauce_connect: true

branches:
  only:
    - master

